<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

/*                                                                        *
 * This script belongs to the TYPO3 Flow package "In2code.SurfGui".       *
 *                                                                        *
 * It is free software; you can redistribute it and/or modify it under    *
 * the terms of the GNU General Public License, either version 3 of the   *
 * License, or (at your option) any later version.                        *
 *                                                                        */

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140912133127 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql');

		$this->addSql('ALTER TABLE in2code_surfgui_domain_model_git_branch DROP currentcommithash');
		$this->addSql('ALTER TABLE in2code_surfgui_domain_model_git_tag DROP taggedcommithash');
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql');

		$this->addSql('ALTER TABLE in2code_surfgui_domain_model_git_branch ADD currentcommithash VARCHAR(255) NOT NULL');
		$this->addSql('ALTER TABLE in2code_surfgui_domain_model_git_tag ADD taggedcommithash VARCHAR(255) NOT NULL');
	}
}
